import Navegation from "../components/Navegation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
  
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navegation/>
        {children}
        </body>
    </html>
  )
}
